run:
  timeout: 2m
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
  modules-download-mode: vendor

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report
    min-complexity: 20
  maligned:
    # print struct with more effective memory layout
    suggest-new: true
  lll:
    line-length: 512

linters:
  enable-all: true
  disable:
    - funlen
    - wsl
    - goerr113
    - noctx
    - gofumpt
    - exhaustivestruct

issues:
  exclude-use-default: true
  exclude-rules:
    - path: builder/runner.go
      text: "G204: Subprocess launched with function call"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gochecknoglobals
        - goconst
        - gomnd
  exclude:
    - should not be capitalized
  # Maximum issues count per one linter. Set to 0 to disable.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable
  max-same: 0

  # Show only new issues
  new: false
